baseURL: "https://chiararelevat.fr"
languageCode: "en-us"
title: "Chiara RELEVAT"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     title: Blog posts
  #     url: /blogs
  #     weight: 1
  #   - identifier: gallery
  #     name: Gallery
  #     title: Blog posts
  #     url: /gallery
  #     weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: "."  # The path to serve the static files from
  favicon: "images/logo-diverse.svg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "dark" # light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Chiara RELEVAT" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Chiara."
    subtitle: "PhD student in Software Language Engeenering"
    content: "I am a PhD student at the [University of Rennes](https://www.univ-rennes.fr/) since september 2023. Member of the [DiverSE team](https://www.diverse-team.fr/)."
    image: images/logo-diverse.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Chiara06830
        - icon: fa-brands fa-gitlab
          url: https://gitlab.com/Chiara06830
        - icon: fa-brands fa-linkedin-in
          url: https://www.linkedin.com/in/chiararelevat/
        - icon: fa-brands fa-orcid
          url: https://orcid.org/0009-0008-5240-2606
        - icon: fa-brands fa-google-scholar
          url: 

  # About
  about:
    enable: true
    title: "About Me"
    image: "images/logo-diverse.svg"
    content: |-
      I am a PhD student at the [University of Rennes](https://www.univ-rennes.fr/) working for the [Institute of Computer Science and Random Systems](https://www.irisa.fr/)(IRISA). Member of the [DiverSE team](https://www.diverse-team.fr/), supervised by [Benoit COMBEMALE](https://people.irisa.fr/Benoit.Combemale/) and [Gurvan LE GUERNIC](http://www.irisa.fr/lande/gleguern/). 

      I am currently working on my subject "DSL Specialization".
      To do so I am working with the [GEMOC Studio](https://projects.eclipse.org/projects/modeling.gemoc).
    skills:
      enable: true
      title: "Wich implies to work with:"
      items:
        - "Java"
        - "[Xtext](https://eclipse.dev/Xtext/)"
        - "[Xtend](https://eclipse.dev/Xtext/xtend/)"
        - "[Sirius](https://www.obeosoft.com/en/products/eclipse-sirius)"
        - "[Kermeta 3](https://diverse-project.github.io/k3/)"

  # Experience
  experience:
    enable: true
    title: "Past Experience"
    items:
      - job: "Intern Back End Developer"
        company: "Vivadrive"
        companyUrl: "https://vivadrive.io/"
        date: "April 2023 - August 2023"
        info:
          enable: true
          content: It was my last intenship to complete my master degree.
        # featuredLink:
        #   enable: true
        #   name: "View the project"
        #   url: "https://example.com"
        content: "I developed an API to calcul the cost of the wear for a car over the years thanks to *Django*."

      - job: "Intern in research on SYCL"
        company: "University of Western Britanny"
        companyUrl: "https://www.univ-brest.fr/faculte-sciences/en/homepage?q=en"
        date: "May 2022 - July 2022"
        featuredLink:
          enable: true
          name: "Publication"
          url: "https://doi.org/10.1145/3585341.3585358"
        info:
          enable: false
        content: |-
          I was working with two other students on accessibility to [SYCL](https://www.khronos.org/sycl/) from Intel.
          
          Together we developed a C++ library that represent a SYCL code and allow to:
          - parse SYCL code to create it's structure in C++
          - generate SYCL code writing only C++ code
          - easily change the structure of the program without writing SYCL code
          - generate graphical representation

      - job: "Intern web developer"
        company: "Capgemini"
        companyUrl: "https://www.capgemini.com/"
        date: "April 2021 - August 2021"
        info:
          enable: true
          content: It was my the internship to complete my Bachelor degree
        content: |
          I was working for the group [AirFrance/KLM](https://www.airfranceklm.com/fr) on an app for airplane management.
          In term of Front End development I worked with Angular, and Spring Boot for Back End.

      - job: "Intern in Java Development"
        company: "Monaco Logistic"
        companyUrl: "https://www.monacologistique.mc/"
        date: "May 2020 - June 2020"
        info:
          enable: true
          content: It was my the internship to complete my under graduate two year diploma.
        content: |
          I developed a Java app to visualize the stock of each warehouse of the company.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master in Software for Embedded Systems"
        school:
          name: "University of Western Britanny, Brest FRANCE"
          url: "https://www.univ-brest.fr/faculte-sciences/en/homepage?q=en"
        date: "2021 - 2023"
        content: |-
          I published my first scientific poster ["Toward a CAD Tool for SYCL programming"](https://doi.org/10.1145/3585341.3585358) during an internship at the end of the first year.

          Completed with an Erasmus semester in Verona (Italy) at [Univesità degli Studi di Verona](https://www.univr.it/en/home) and an intenational internship at [Vivadrive](#experience) in Warsaw (Poland).
      - title: "Bachelor of Engeineering in Computer Science"
        school:
          name: "University of Western Britanny, Brest FRANCE"
          url: "https://www.univ-brest.fr/faculte-sciences/en/homepage?q=en"
        date: "2020 - 2021"
        content: |-
          I applied everything I learn at this point during my [internship at Capgemini](#experience).
      - title: "Undergraduated two year diploma"
        school:
          name: "IUT University Cote d'Azur, Nice FRANCE"
          url: "https://univ-cotedazur.eu/"
        date: "2018 - 2020"
        content: |-
          I learnt the bases in every domain of computer science. And applied my knowledge in object oriented app developmnet during my final [internship at Monaco Logistic](#experience).
      - title: "High School"
        school:
          name: "Lycée de la montagne, Valdeblore FRANCE"
          url: "https://lyceedelamontagne.fr/"
        date: "2015 - 2018"

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Dead bot Daylight
        content: Mobil robotic project where two robots can be controled thanks to a web app.
        image: images/logo-diverse.svg
        badges:
          - "Academic"
          - "React"
          - "Arduino"
          - "JavaScript"
        links:
          - icon: fa-brands fa-gitlab
            url: https://gitlab.com/GGestin/dead-bot-daylight
      - title: Galagaga
        content: Remake of the arcade game Galaga.
        image: images/logo-diverse.svg
        badges:
          - "Academic"
          - "HTML/CSS"
          - "JavaScript"
          - "Firebase"
        featured:
          name: Demo
          link: https://teten_.gitlab.io/projectgalagaga/pages/game.html
        links:
          - icon: fa-brands fa-gitlab
            url: https://gitlab.com/Teten_/projectgalagaga
      - title: DOMUS Lang
        content: Compilator of language DOMUS wich allow to schedule the controls of blinds and lights of a house.
        image: images/logo-diverse.svg
        badges:
          - "Academic"
          - "Lex"
          - "JCup"
          - "Java"
        links:
          - icon: fa-brands fa-gitlab
            url: https://gitlab.com/manoconi/comp2pro
      - title: Morubo
        content: Android app to play tic tac toe online with a friend.
        image: images/logo-diverse.svg
        badges:
          - "Academic"
          - "Android Studio"
          - "Java"
          - "Firebase"
        featured:
          name: Demo
          link: https://gitlab.com/Chiara06830/bestmorpionoftheentireworld/-/blob/main/VID_20211210_104216.mp4?ref_type=headsm
        links:
          - icon: fa-brands fa-gitlab
            url: https://gitlab.com/Chiara06830/bestmorpionoftheentireworld
      - title: TCP server/client
        content: Linux and Windows app to transfer files between a client and a server with the TCP protocol.
        image: images/logo-diverse.svg
        badges:
          - "Academic"
          - "Java"
          - "Java FX"
          - "Java threads"
          - "Eclipse"
        links:
          - icon: fab fa-github
            url: https://github.com/Chiara06830/Serveur_Client_TCP
      - title: Follow your sports
        content: Linux and Windows app to follow your sports routine.
        image: images/logo-diverse.svg
        badges:
          - "Academic"
          - "Java"
          - "Java FX"
          - "Eclipse"
          - "PostgreSQL"
          - "SQL"
        links:
          - icon: fab fa-github
            url: https://github.com/VLCR-UBO/Suit-ton-sportif
      - title: Attend your students
        content: Hybrid app to make the attendance of a class at the University of Western Britanny.
        image: images/logo-diverse.svg
        badges:
          - "Academic"
          - "React Native"
        links:
          - icon: fab fa-github
            url: https://github.com/Chiara06830/Emarge-tes-eleves--
      - title: Monoplan
        content: Spreadsheet app.
        image: images/logo-diverse.svg
        badges:
          - "Academic"
          - "C"
        links:
          - icon: fab fa-github
            url: https://github.com/Chiara06830/Monoplan
      # - title: Shadow Hunter Game
      #   content: Digitalisation of the board game Shadow Hunter.
      #   image: images/logo-diverse.svg
      #   badges:
      #     - "Academic"
      #     - "Java"
      #     - "Java FX"
      #     - "Eclipse"
      - title: Discover the europeans country
        content: Android game with a quizz to guess and learn the europeans countries.
        image: images/logo-diverse.svg
        badges:
          - "Academic"
          - "Android Studio"
          - "Java"
        links:
          - icon: fab fa-github
            url: https://github.com/Chiara06830/Decouvrir-les-pays-d-Europe/tree/master
      # - title: PPTX2HTML
      #   content: Convertor of Power Point slides to web page for presentation.
      #   image: images/logo-diverse.svg
      #   badges:
      #     - "Academic"
      #     - "Java"
      #     - "HTML/CSS"
      #     - "JavaScript"
      # - title: SLEGPI
      #   content: Web app which controls the blinds and lights of a house.
      #   image: images/logo-diverse.svg
      #   badges:
      #     - "Academic"
      #     - "Arduino"
      #     - "JavaScript"
      # - title: AutoMark
      #   content: Software for automatic generation and correction of MCQ exams.
      #   image: images/logo-diverse.svg
      #   badges:
      #     - "Academic"
      #     - "Java"
      #     - "Eclipse"
      # - title: e-Chesstria
      #   content: In terminal chess game.
      #   image: images/logo-diverse.svg
      #   badges:
      #     - "Academic"
      #     - "Java"
      #     - "Eclipse"

  # Achievements
  achievements:
    enable: true
    title: "Publications"
    items:
      - title: Toward a CAD Tool for SYCL programming
        content: This poster discusses the design and operation of a CAD tool for the SYCL standard. 
        url: https://dl.acm.org/doi/10.1145/3585341.3585358
        image: /images/toward CAD tools for SYCL programming.png

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: chiara.relevat@outlooK.fr
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
    #   disableFeaturedImage: false
    # socialNetworks:
    #   github: https://github.com
    #   linkedin: https://linkedin.com
    #   twitter: https://twitter.com
    #   instagram: https://instagram.com
    #   facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>